config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items, only: [:index, :show], param: :item_code
  resources :reviews, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    page = params[:current_page]&.to_i || 1
    page_type = params[:page_type]
    keyword = params[:keyword].present? ? params[:keyword] : "ファラオ"
    @items = RakutenWebService::Ichiba::Item.search(keyword: keyword, hits: 20, page: curricurate_page(page,page_type))
    @reviews = Review.all
  end

  def show
    @item = RakutenWebService::Ichiba::Item.search(item_code: params[:item_code])
    @item_reviews = Review.where("item_code = ?", params[:item_code])
  end

  private

  def curricurate_page(page, page_type)
    if page > 1 && page_type == "prev"
      page -= 1
    elsif page_type == "next"
      page += 1
    else
      page
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @item = RakutenWebService::Ichiba::Item.search(item_code: params[:item_code])
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to item_path(@review.item_code)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:user_name, :content, :item_code, :score)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resize_text(text, num)
    text.size > num ? text.slice(0, num) + "..." : text
  end
end

app/views/items/index.html.erb
<div class="container my-4 mx-auto">
<h1>商品一覧</h1>
  <%= form_with url: items_path, method: :get, class: "d-flex gap-1 mb-3" do |f| %>
    <%= f.text_field "keyword", placeholder: "検索キーワード" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
  
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-auto col-lg-3 mb-3">
        <div class="card">
          <%= image_tag item["mediumImageUrls"][0], class: 'card-img-top' %>
          <div class="card-body">
            <p class="card-title">
              <%= link_to resize_text(item["itemName"], 35), item_path(item["itemCode"]) %>
            </p>
            <p>
              <%= "#{item["itemPrice"]}円" %>
            </p>
            <p>
              <% score_array = @reviews.where(item_code: item["itemCode"]).pluck(:score) %>
              総合評価: <%= score_array.size > 0 ? score_array.sum.fdiv(score_array.size).round(2) : 'まだ評価がありません' %>
            </p>
            <p>
              <%= link_to "レビュー", new_review_path(item_code: item["itemCode"]) %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center gap-3">
    <%= link_to "Prev", items_path(keyword: @items.params[:keyword], current_page: @items.params[:page], page_type: "prev") %>
    <%= link_to "Next", items_path(keyword: @items.params[:keyword], current_page: @items.params[:page], page_type: "next") %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container m-5">
  <div class="d-flex align-items-stretch w-50 mx-auto">
    <div>
      <%= image_tag @item.response['Items'].first["mediumImageUrls"][0], class: 'img-thumbnail' %>
    </div>
    <p class='w-75 ms-3 border p-2'>
      <%= resize_text(@item.response['Items'].first["itemName"], 100) %>
    </p>
  </div>
  <div class='w-50 mx-auto'>
    <% @item_reviews.each do |item_review| %>
      <div class="border mb-1">
        <p>ニックネーム: <%= item_review.user_name %>
        <p>評価: <%= item_review.score %>
        <p>コメント: <%= item_review.content %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container m-5">
  <div class="d-flex align-items-stretch w-50 mx-auto">
    <div>
      <%= image_tag @item.response['Items'].first["mediumImageUrls"][0], class: 'img-thumbnail' %>
    </div>
    <p class='w-75 ms-3 border p-2'>
      <%= resize_text(@item.response['Items'].first["itemName"], 100) %>
    </p>
  </div>
  <%= form_with model: @review, class: 'form-group w-50 mx-auto' do |f| %>
    <div class="mb-3">
      <%= f.label "ニックネーム", class: "form-label" %>
      <%= f.text_field "user_name", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label "評価", class: "form-label" %>
      <%= f.number_field "score", class: "form-control", in: 1.0..5.0, step: 0.5 %>
    </div>
    <div class="mb-3">
      <%= f.label "レビュー", class: "form-label" %>
      <%= f.text_area "content", class:"form-control" %>
    </div>
      <%= f.hidden_field "item_code", value: params[:item_code] %>
    <div class="mb-3">
      <%= f.submit "登録", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>